import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { CartProvider } from "../context/CartContext";
import { Space_Grotesk } from 'next/font/google';
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose weights you need
  variable: '--font-space-grotesk',     // optional: for Tailwind
  display: 'swap',
});





const poppinsFont = Poppins({ subsets: ["latin"], weight: "400" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children}) {
  
  return (
    <html lang="en"
    >
       <head>
          {/* Add the viewport meta tag here */}
         <link href="https://fonts.maateen.me/solaiman-lipi/font.css" rel="stylesheet"></link>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
          <title>Astro BD</title>
        </head>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${poppinsFont.className} text-black`}
      ><CartProvider>
        <Navbar/>
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
